#!/bin/bash

set -o pipefail

echo "Build, lint and test ..."

cargo build --tests -q && cargo clippy 2>&1 | sed '/Compiling|Finished/ d' && cargo test -q | sed -n '/^failures/,/failures/{s/^failures //;/^failures/d;p;}'

if [ $? -eq 0 ]
then
	echo "All good ;-)"
else
	echo "Oops. FAILED!!"
fi
