#!/bin/sh

set -o pipefail

echo "Testing ...\n"

# 2 > /dev/null silence the warnings when running tests.

cargo test -q 2>/dev/null | sed -n '/^failures/,/failures/{s/^failures //;/^failures/d;p;}'

if [ $? -eq 0 ]
then
	echo "All good ;-)\n"
else
	echo "Oops. FAILED!!\n"
fi
