#!/bin/bash

# In Debian /bin/sh points at /bin/dash where pipefail is not supported.

# To be run in the same directory as filename.tex. Providing the full
# path to filename.tex is not supported

# Usage: latexbuild filename.tex

BACKEND=-pdf # Makes use of pdflatex under the covers
FILENAME=$1

if test "$1" == "xelatex";
then
    BACKEND="-xelatex"
    FILENAME=$2
fi

set -o pipefail


latexmk $BACKEND -interaction=nonstopmode -bibtex-cond -halt-on-error -file-line-error $FILENAME 2>/dev/null | sed -n '/^\.\/'"$FILENAME"'/,/Transcript/{/Transcript/!p;}'

if [ $? -eq 0 ]
then
	echo "All good ;-)"
else
	echo "Oops. FAILED!!"
fi
