#!/bin/sh

# (l) command (l)ists Rust unit tests

# Usage:
# lrtests $% (current window)
# lrtests *.rs (all rust files in current directory)

# will print out
# <module_name>:<line_number>: <test_name>

/usr/bin/awk '/\[test/{getline;var=FILENAME; n=split (var,a,/\//); print a[n]":"FNR":"$0}' "$@"
