#!/bin/bash

# Trim string from the right

# Select text and middle click
# |trimr 'text to trim'

# Example

# code to remove real code
# code to remove real code

# When selecting both lines and middle clicking on
# |trimr 'real code'

# we end up with

# code to remove
# code to remove

/bin/sed "s/ $1$//g"
