#!/usr/bin/env python

import subprocess
import sys

if len(sys.argv) == 3:
    # kdp pod namespace
    # pod name + namespace
    cmd = ["kubectl", "describe", "pod", sys.argv[1], "-n", sys.argv[2]]
else:
    fields = sys.argv[1].split(' ')
    if len(fields) == 0:
        cmd = ["kubectl", "describe", "pod", fields[0]]
    else:
        cmd = ["kubectl", "describe", "pod", fields[0], "-n", fields[1]]

print subprocess.check_output(cmd)
