#!/usr/bin/env python

# Provides kubectl get pods by quoting the pods, so we can quickly select
# them through acme.

import sys

cmd = []

namespace = ""

if len(sys.argv) == 2:
    namespace = sys.argv[1]
    cmd = ["kubectl", "get", "pods", "-n", namespace]
else:
    cmd = ["kubectl", "get", "pods"]

# kubectl get pods
import subprocess
output = subprocess.check_output(cmd)

lines = output.split('\n')

import kcommon
kcommon.span(lines, namespace)
kcommon.format(lines, namespace)
