#!/usr/bin/env python

# Provides kubectl get pods by quoting the pods, so we can quickly select
# them through acme.

import sys
import kcommon
import subprocess

cmd, namespace = kcommon.get_command(sys.argv, 'pods')
output = subprocess.check_output(cmd)
lines = output.split('\n')
kcommon.span(lines, namespace)
kcommon.format(lines, namespace)
